bind 0.0.0.0
port 6379
timeout 0
tcp-keepalive 300

daemonize no
supervised no
loglevel notice

databases 16

dir /data
dbfilename dump.rdb

appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"

save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

protected-mode yes
always-show-logo no
